version: '3'
services:
  web:
    build: .
    command: node app.js
    ports:
      - "8080:80"
    environment:
      SERVER_PORT: 80
      JWT_PRIVATE_KEY: node-blog-website
      MONGO_DB_URI: 'mongodb+srv://read:a3yqSYeElcMVQMFV@cluster0.csfqz.mongodb.net/node-blog-website?retryWrites=true&w=majority'

# username: lars.gerber@bluewin.ch
# password: node-blog-website
